# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['foo', 'bar']

# %% ../nbs/00_core.ipynb 3
import rdkit.Chem as Chem
import tmap as tm

# %% ../nbs/00_core.ipynb 4
def foo(): pass

# %% ../nbs/00_core.ipynb 5
def bar(): print('hey')
